---
- name: nginx zenit
  hosts: localhost
  become: yes

  tasks:

  - name: Install epel
    yum: name=epel-release state=present
  
  - name: Install nginx
    yum: name=nginx state=present

  - name: copy conf nginx
    copy: src=/home/dmitry/znginx/nginx.conf dest=/etc/nginx

  - name: copy conf webpage
    copy: src=/home/dmitry/znginx/default.conf dest=/etc/nginx/conf.d

  - name: copy webpage
    copy: src=/home/dmitry/znginx/default dest=/var/www/html/
   
  - name: restart nginx
    service: name=nginx state=restarted
